### ISSUE TITLE
Minimum Agnostic XBlock Requirements

### ISSUE THREAD

**Issue by lidijarad** [proversity-org/agnostic-content-xblock#2]
Content Components 
- [x] Video 
- [x] Google Doc
- [x] PDF 
- [x] HTML

Assessment Components
- [x] MQC, dropdown, numerical input, text input
- [x] Free text response 
- [x] Checkboxes

Interactive Component
- [x] Discussion

Additions to edx-platform
- [x] add https://github.com/IONISx/xblock-pdf to requirements
- [x] add advanced component types to library_content_module

- [x] add a scope.user_state (up_votes and down votes) to agnostic content block

**Comment by lidijarad** [comment]
@renevatium, could you please help me make a list of things that need to be delivered for the deadline for Pearson, and what is the exact date? Is it due 20 Decemeber?

**Comment by renevatium** [comment]
@lidijarad list looks good. Content component must be added first (and stored as the primary content item - we will process this later, but don't worry about that for now). Only 1 discussion component allowed. Otherwise that's good for now 👍

**Comment by lidijarad** [comment]
@renevatium, logging that I need to fix the "type" in the Random Content Xblock. 
- [ ] allow specific advanced components to be selected as the type, pulls in Advanced comps if type = "Any" and there are only ACX xblocks in lib. 
- [ ] extend the "mode" which randomly shuffles content, to select specific content.
